### ISSUE TITLE
AlertManager Configuration Download Error

### ISSUE THREAD

**Issue by skdwriting** [opensds/opensds-dashboard#128] opened 2019-06-18 00:53 UTC
GUI->Monitor->Configuration
It shows prometheus, alertmanager and grafana
All has upload and download options.

Able to download prometheus and grafana configs
When tried to download alertmanager, it says File Cannot be downloaded.

Suggestions:
If there is no config uploaded, download option can be disabled.
OR say there is no file.
![Dashboard-alertmanager-profile-download-warning](https://user-images.githubusercontent.com/8660550/59645817-8ccc5e80-9191-11e9-8f2a-9ebe459dd892.PNG)

**Comment by anvithks** [comment] 2019-06-18 05:12
This is fixed in latest code. I believe there was some in the backend that was fixed by @NajmudheenCT .

**Comment by anvithks** [comment] 2019-06-18 05:15
@skdwriting The config files are created on the system at the time of installation. For download and upload we are using an API. 
Currently the table of service configurations is being populated manually via dashboard. The plan is to make an API for this or modify the current urls api to provide the information for all the services.  
I believe for CAPRI the issue is fixed. We can take the issue of unavailable service configs to be disabled or hidden as a backlog.

**Comment by anvithks** [comment] 2019-06-18 08:19
@skdwriting verified on new fresh install from development branch. The download configuration works for all three.

**Comment by anvithks** [comment] 2019-06-18 19:23
I think this issue can be closed @skdwriting Please verify.

**Comment by anvithks** [comment] 2019-06-18 20:10
Verified in latest release. This is fixed.
![download-alert-manager](https://user-images.githubusercontent.com/19162717/59716211-3152ad00-9233-11e9-90b4-c86abca9602c.png)
Closing the issue.

**Closed by anvithks** 2019-06-18 20:10 UTC
Labels: CAPRI
