### ISSUE TITLE
Telemetry Dashboard: Cards disappear

### ISSUE THREAD

**Issue by kumarashit** [opensds/opensds-dashboard#148] opened 2019-06-20 05:23 UTC
Issue with v0.5.5. 
Keep the dashboard open. After some time, the two cards "Grafana" and "Alert Manager" disappears. After a refresh, they come back.
Please note that the session didn't time out and i din't have to re-login. It only refresh of the page.

**Comment by anvithks** [comment] 2019-06-20 08:33
@kumarashit Is there an environment where I can check this?
Please check the API calls in the network tab of the developer toolbar and if possible please share the screenshot here.

**Comment by anvithks** [comment] 2019-06-25 11:19
I could not reproduce this. I can see this happen only when the session is timed out and the network calls to the API are unauthorised as the token has expired.
I am closing this for now. I will keep checking and if I can reproduce this then I will open the issue.

**Closed by anvithks** 2019-06-25 11:19 UTC
Labels: bug
