### ISSUE TITLE
Dashboard for Lifecycle: Completely Blocked for creating new Life cycle rule after an error occured

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#86] opened 2019-06-10 06:17 UTC
1. Click create Lifecycle rule
2. keep clicking Add Rule for 5 times
3. add configuration values
4. Not able to delete the rules
5. Not able to Click OK button
6. Click Cancel.. and Create button again...previous data only showing.. show its completely blocked now to create Life cyecle config
![LifcycleIssues_not able to create lifcycle](https://user-images.githubusercontent.com/48289385/59176060-84fb3180-8b75-11e9-9bab-a141f2f91b77.PNG)

**Comment by anvithks** [comment] 2019-06-12 14:23
@skdwriting Needs to be fixed

**Comment by skdwriting** [comment] 2019-06-13 06:44
@jimccfun please update the status here

**Comment by jimccfun** [comment] 2019-06-15 04:11
@satya-gorli About this problem, if we execute the first three steps, and in the fourth step, we can click the delete button to delete rules. I tried to delete rules normally. Can you repeat that you cannot delete rules? For step 6, I tried to click the cancel button and click the create button again, without showing the previous data, so can you repeat step 6?

**Comment by anvithks** [comment] 2019-06-18 20:13
@jimccfun @nguptaopensds Please verify if this issue is fixed. If not please inform if this needs to be fixed.

**Comment by anvithks** [comment] 2019-06-20 13:28
@satya-gorli Not able to reproduce this in the latest version of the code. Closing this now. Please reopen if you can still reproduce this issue.
@jimccfun Were you able to reproduce this issue? If yes then please let us know.

**Closed by anvithks** 2019-06-20 13:28 UTC
Labels: CAPRI
